# Generated by Django 5.1.2 on 2024-11-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energytip',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='energytip',
            name='tip',
        ),
        migrations.AddField(
            model_name='energytip',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='energytip',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
